#############################################################################
# Makefile for building: op_mc_hc
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  MC_with_PE.pro
# Template: app
# Command: /opt/Qt-5.7.1/bin/qmake -o Makefile MC_with_PE.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = mpicc
CXX           = mpicxx
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../partsEngine-master -I/opt/Qt-5.7.1/include -I/opt/Qt-5.7.1/include/QtCore -I. -I/opt/Qt-5.7.1/mkspecs/linux-g++
QMAKE         = /opt/Qt-5.7.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = op_mc_hc1.0.0
DISTDIR = /home/pitandmind/order_paramegtr_MC/mc_w_PE/.tmp/op_mc_hc1.0.0
LINK          = mpicxx
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt-5.7.1/lib
LIBS          = $(SUBLIBS) -L/home/pitandmind/order_paramegtr_MC/mc_w_PE/../partsEngine-master/ -lPartsEngine -L/opt/Qt-5.7.1/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /opt/Qt-5.7.1/mkspecs/features/spec_pre.prf \
		/opt/Qt-5.7.1/mkspecs/common/unix.conf \
		/opt/Qt-5.7.1/mkspecs/common/linux.conf \
		/opt/Qt-5.7.1/mkspecs/common/sanitize.conf \
		/opt/Qt-5.7.1/mkspecs/common/gcc-base.conf \
		/opt/Qt-5.7.1/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt-5.7.1/mkspecs/common/g++-base.conf \
		/opt/Qt-5.7.1/mkspecs/common/g++-unix.conf \
		/opt/Qt-5.7.1/mkspecs/qconfig.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt-5.7.1/mkspecs/features/qt_functions.prf \
		/opt/Qt-5.7.1/mkspecs/features/qt_config.prf \
		/opt/Qt-5.7.1/mkspecs/linux-g++/qmake.conf \
		/opt/Qt-5.7.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt-5.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/Qt-5.7.1/mkspecs/features/toolchain.prf \
		/opt/Qt-5.7.1/mkspecs/features/default_pre.prf \
		/opt/Qt-5.7.1/mkspecs/features/resolve_config.prf \
		/opt/Qt-5.7.1/mkspecs/features/default_post.prf \
		/opt/Qt-5.7.1/mkspecs/features/warn_on.prf \
		/opt/Qt-5.7.1/mkspecs/features/qt.prf \
		/opt/Qt-5.7.1/mkspecs/features/resources.prf \
		/opt/Qt-5.7.1/mkspecs/features/moc.prf \
		/opt/Qt-5.7.1/mkspecs/features/unix/thread.prf \
		/opt/Qt-5.7.1/mkspecs/features/file_copies.prf \
		/opt/Qt-5.7.1/mkspecs/features/testcase_targets.prf \
		/opt/Qt-5.7.1/mkspecs/features/exceptions.prf \
		/opt/Qt-5.7.1/mkspecs/features/yacc.prf \
		/opt/Qt-5.7.1/mkspecs/features/lex.prf \
		MC_with_PE.pro  main.cpp
QMAKE_TARGET  = op_mc_hc
DESTDIR       = 
TARGET        = op_mc_hc


first: all
####### Build rules

$(TARGET): /home/pitandmind/order_paramegtr_MC/mc_w_PE/../partsEngine-master/libPartsEngine.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MC_with_PE.pro /opt/Qt-5.7.1/mkspecs/linux-g++/qmake.conf /opt/Qt-5.7.1/mkspecs/features/spec_pre.prf \
		/opt/Qt-5.7.1/mkspecs/common/unix.conf \
		/opt/Qt-5.7.1/mkspecs/common/linux.conf \
		/opt/Qt-5.7.1/mkspecs/common/sanitize.conf \
		/opt/Qt-5.7.1/mkspecs/common/gcc-base.conf \
		/opt/Qt-5.7.1/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt-5.7.1/mkspecs/common/g++-base.conf \
		/opt/Qt-5.7.1/mkspecs/common/g++-unix.conf \
		/opt/Qt-5.7.1/mkspecs/qconfig.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt-5.7.1/mkspecs/features/qt_functions.prf \
		/opt/Qt-5.7.1/mkspecs/features/qt_config.prf \
		/opt/Qt-5.7.1/mkspecs/linux-g++/qmake.conf \
		/opt/Qt-5.7.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt-5.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/Qt-5.7.1/mkspecs/features/toolchain.prf \
		/opt/Qt-5.7.1/mkspecs/features/default_pre.prf \
		/opt/Qt-5.7.1/mkspecs/features/resolve_config.prf \
		/opt/Qt-5.7.1/mkspecs/features/default_post.prf \
		/opt/Qt-5.7.1/mkspecs/features/warn_on.prf \
		/opt/Qt-5.7.1/mkspecs/features/qt.prf \
		/opt/Qt-5.7.1/mkspecs/features/resources.prf \
		/opt/Qt-5.7.1/mkspecs/features/moc.prf \
		/opt/Qt-5.7.1/mkspecs/features/unix/thread.prf \
		/opt/Qt-5.7.1/mkspecs/features/file_copies.prf \
		/opt/Qt-5.7.1/mkspecs/features/testcase_targets.prf \
		/opt/Qt-5.7.1/mkspecs/features/exceptions.prf \
		/opt/Qt-5.7.1/mkspecs/features/yacc.prf \
		/opt/Qt-5.7.1/mkspecs/features/lex.prf \
		MC_with_PE.pro \
		/opt/Qt-5.7.1/lib/libQt5Core.prl
	$(QMAKE) -o Makefile MC_with_PE.pro
/opt/Qt-5.7.1/mkspecs/features/spec_pre.prf:
/opt/Qt-5.7.1/mkspecs/common/unix.conf:
/opt/Qt-5.7.1/mkspecs/common/linux.conf:
/opt/Qt-5.7.1/mkspecs/common/sanitize.conf:
/opt/Qt-5.7.1/mkspecs/common/gcc-base.conf:
/opt/Qt-5.7.1/mkspecs/common/gcc-base-unix.conf:
/opt/Qt-5.7.1/mkspecs/common/g++-base.conf:
/opt/Qt-5.7.1/mkspecs/common/g++-unix.conf:
/opt/Qt-5.7.1/mkspecs/qconfig.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_core.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_network.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_purchasing.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_script.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt-5.7.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt-5.7.1/mkspecs/features/qt_functions.prf:
/opt/Qt-5.7.1/mkspecs/features/qt_config.prf:
/opt/Qt-5.7.1/mkspecs/linux-g++/qmake.conf:
/opt/Qt-5.7.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt-5.7.1/mkspecs/features/exclusive_builds.prf:
/opt/Qt-5.7.1/mkspecs/features/toolchain.prf:
/opt/Qt-5.7.1/mkspecs/features/default_pre.prf:
/opt/Qt-5.7.1/mkspecs/features/resolve_config.prf:
/opt/Qt-5.7.1/mkspecs/features/default_post.prf:
/opt/Qt-5.7.1/mkspecs/features/warn_on.prf:
/opt/Qt-5.7.1/mkspecs/features/qt.prf:
/opt/Qt-5.7.1/mkspecs/features/resources.prf:
/opt/Qt-5.7.1/mkspecs/features/moc.prf:
/opt/Qt-5.7.1/mkspecs/features/unix/thread.prf:
/opt/Qt-5.7.1/mkspecs/features/file_copies.prf:
/opt/Qt-5.7.1/mkspecs/features/testcase_targets.prf:
/opt/Qt-5.7.1/mkspecs/features/exceptions.prf:
/opt/Qt-5.7.1/mkspecs/features/yacc.prf:
/opt/Qt-5.7.1/mkspecs/features/lex.prf:
MC_with_PE.pro:
/opt/Qt-5.7.1/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MC_with_PE.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp ../partsEngine-master/random.h \
		../partsEngine-master/PartArray.h \
		/opt/Qt-5.7.1/include/QtCore/QString \
		/opt/Qt-5.7.1/include/QtCore/qstring.h \
		/opt/Qt-5.7.1/include/QtCore/qchar.h \
		/opt/Qt-5.7.1/include/QtCore/qglobal.h \
		/opt/Qt-5.7.1/include/QtCore/qconfig.h \
		/opt/Qt-5.7.1/include/QtCore/qfeatures.h \
		/opt/Qt-5.7.1/include/QtCore/qsystemdetection.h \
		/opt/Qt-5.7.1/include/QtCore/qprocessordetection.h \
		/opt/Qt-5.7.1/include/QtCore/qcompilerdetection.h \
		/opt/Qt-5.7.1/include/QtCore/qtypeinfo.h \
		/opt/Qt-5.7.1/include/QtCore/qtypetraits.h \
		/opt/Qt-5.7.1/include/QtCore/qisenum.h \
		/opt/Qt-5.7.1/include/QtCore/qsysinfo.h \
		/opt/Qt-5.7.1/include/QtCore/qlogging.h \
		/opt/Qt-5.7.1/include/QtCore/qflags.h \
		/opt/Qt-5.7.1/include/QtCore/qatomic.h \
		/opt/Qt-5.7.1/include/QtCore/qbasicatomic.h \
		/opt/Qt-5.7.1/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt-5.7.1/include/QtCore/qgenericatomic.h \
		/opt/Qt-5.7.1/include/QtCore/qatomic_cxx11.h \
		/opt/Qt-5.7.1/include/QtCore/qatomic_msvc.h \
		/opt/Qt-5.7.1/include/QtCore/qglobalstatic.h \
		/opt/Qt-5.7.1/include/QtCore/qmutex.h \
		/opt/Qt-5.7.1/include/QtCore/qnumeric.h \
		/opt/Qt-5.7.1/include/QtCore/qversiontagging.h \
		/opt/Qt-5.7.1/include/QtCore/qbytearray.h \
		/opt/Qt-5.7.1/include/QtCore/qrefcount.h \
		/opt/Qt-5.7.1/include/QtCore/qnamespace.h \
		/opt/Qt-5.7.1/include/QtCore/qarraydata.h \
		/opt/Qt-5.7.1/include/QtCore/qstringbuilder.h \
		/opt/Qt-5.7.1/include/QtCore/QFile \
		/opt/Qt-5.7.1/include/QtCore/qfile.h \
		/opt/Qt-5.7.1/include/QtCore/qfiledevice.h \
		/opt/Qt-5.7.1/include/QtCore/qiodevice.h \
		/opt/Qt-5.7.1/include/QtCore/qobject.h \
		/opt/Qt-5.7.1/include/QtCore/qobjectdefs.h \
		/opt/Qt-5.7.1/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt-5.7.1/include/QtCore/qlist.h \
		/opt/Qt-5.7.1/include/QtCore/qalgorithms.h \
		/opt/Qt-5.7.1/include/QtCore/qiterator.h \
		/opt/Qt-5.7.1/include/QtCore/qhashfunctions.h \
		/opt/Qt-5.7.1/include/QtCore/qpair.h \
		/opt/Qt-5.7.1/include/QtCore/qbytearraylist.h \
		/opt/Qt-5.7.1/include/QtCore/qstringlist.h \
		/opt/Qt-5.7.1/include/QtCore/qregexp.h \
		/opt/Qt-5.7.1/include/QtCore/qstringmatcher.h \
		/opt/Qt-5.7.1/include/QtCore/qcoreevent.h \
		/opt/Qt-5.7.1/include/QtCore/qscopedpointer.h \
		/opt/Qt-5.7.1/include/QtCore/qmetatype.h \
		/opt/Qt-5.7.1/include/QtCore/qvarlengtharray.h \
		/opt/Qt-5.7.1/include/QtCore/qcontainerfwd.h \
		/opt/Qt-5.7.1/include/QtCore/qobject_impl.h \
		/opt/Qt-5.7.1/include/QtCore/QTextStream \
		/opt/Qt-5.7.1/include/QtCore/qtextstream.h \
		/opt/Qt-5.7.1/include/QtCore/qlocale.h \
		/opt/Qt-5.7.1/include/QtCore/qvariant.h \
		/opt/Qt-5.7.1/include/QtCore/qmap.h \
		/opt/Qt-5.7.1/include/QtCore/qdebug.h \
		/opt/Qt-5.7.1/include/QtCore/qhash.h \
		/opt/Qt-5.7.1/include/QtCore/qvector.h \
		/opt/Qt-5.7.1/include/QtCore/qpoint.h \
		/opt/Qt-5.7.1/include/QtCore/qset.h \
		/opt/Qt-5.7.1/include/QtCore/qcontiguouscache.h \
		/opt/Qt-5.7.1/include/QtCore/qsharedpointer.h \
		/opt/Qt-5.7.1/include/QtCore/qshareddata.h \
		/opt/Qt-5.7.1/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt-5.7.1/include/QtCore/QtDebug \
		../partsEngine-master/Part.h \
		../partsEngine-master/Vect.h \
		../partsEngine-master/StateMachine.h \
		../partsEngine-master/config.h \
		../partsEngine-master/statemachinebase.h \
		../partsEngine-master/StateMachineFree.h \
		../partsEngine-master/loadhelper.h \
		/opt/Qt-5.7.1/include/QtCore/QDebug \
		../partsEngine-master/savehelper.h \
		../partsEngine-master/squareisinglattice.h \
		../partsEngine-master/squarelattice.h \
		honeycomb_methods.cpp \
		triangular_methods.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

